// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0234OD0R44Tcc1Cswi9RjpNfB_e9a0KU',
    appId: '1:96398770113:web:4734a3c2373b8778d3b940',
    messagingSenderId: '96398770113',
    projectId: 'myapp-abraham-flutter',
    authDomain: 'myapp-abraham-flutter.firebaseapp.com',
    storageBucket: 'myapp-abraham-flutter.appspot.com',
    measurementId: 'G-79006RZ63X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCp4F15WBFKfni7bTgIDVDw_OBcsjsZ4M',
    appId: '1:96398770113:android:c4b8990e31088393d3b940',
    messagingSenderId: '96398770113',
    projectId: 'myapp-abraham-flutter',
    storageBucket: 'myapp-abraham-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXf6GKega_DbLRoqOO5tNN9nQ6NQq3VZI',
    appId: '1:96398770113:ios:43fa4c8d7417b9aad3b940',
    messagingSenderId: '96398770113',
    projectId: 'myapp-abraham-flutter',
    storageBucket: 'myapp-abraham-flutter.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXf6GKega_DbLRoqOO5tNN9nQ6NQq3VZI',
    appId: '1:96398770113:ios:43fa4c8d7417b9aad3b940',
    messagingSenderId: '96398770113',
    projectId: 'myapp-abraham-flutter',
    storageBucket: 'myapp-abraham-flutter.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0234OD0R44Tcc1Cswi9RjpNfB_e9a0KU',
    appId: '1:96398770113:web:82778b29f3012491d3b940',
    messagingSenderId: '96398770113',
    projectId: 'myapp-abraham-flutter',
    authDomain: 'myapp-abraham-flutter.firebaseapp.com',
    storageBucket: 'myapp-abraham-flutter.appspot.com',
    measurementId: 'G-9CTH50K3RG',
  );
}
